
export const unGodlyWords = [
    "anal",
    "arse", 
    "arsehead",
    "arsehole",
    "ass",
    "asshead",
    "asshole",
    "bastard",
    "bitch",
    "bloody",
    "bollocks",
    "brotherfucker",
    "bellend",
    "bloodclart",
    "bumbaclart",
    "bloodclaat",
    "bumbaclaat",
    "bugger",
    "bullshit",
    "child-fucker",
    "Christ on a bike",
    "Christ on a cracker",
    "cock",
    "cocksucker",
    "crap",
    "cunt",
    "damn",
    "damn it",
    "dick",
    "dickhead",
    "dyke",
    "faggot",
    "fatherfucker",
    "fanny",
    "fuck",
    "frigger",
    "holy shit",
    "horseshit",
    "Jesus fuck",
    "kike",
    "knobhead",
    "knob",
    "mother fucker",
    "Nigga",
    "nigger",
    "nig",
    "niggy",
    "prick",
    "pussy",
    "pussyhole",
    "shit",
    "shite",
    "shitass",
    "sisterfucker",
    "slut",
    "son of a whore",
    "son of a bitch",
    "dunce",
    "spastic",
    "retard",
    "turd",
    "twat", 
    "wanker",
    "tits",
    "vagina",
    "penis",
    "willy",
    "nipple",
    "boobies",
    "boobs", 
    "cleavage",
    "fag",
    "fruity",
    "Gay",
    "tranny",
    "Queer",
    "Homo",
    
];